version: "3"
services:
  kml-allennlp:
    build: .
    ports:
      - '9875:9875'
    volumes:
      - './work/:/work/'
    command: jupyter lab --ip=0.0.0.0 --port=9875 --allow-root --no-browser --notebook-dir='/work'
